### ISSUE TITLE
Iniciativa

### ISSUE THREAD

**Issue by ricardokovalski** [RhianLopes/Git#1]
Gostei da sua iniciativa, a tempos eu estava procurando um repositório que explicasse o básico sobre Git.
Uma sugestão minha mas não quer dizer que você deve aplica-lá, em vez de escrever todo o seu conteúdo no README.md, você pode estruturar ele em outros arquivos e no README fazer os links.
Você pode ver essa abordagem em alguns dos meus repositórios como: https://github.com/ricardokovalski/Resume

**Comment by RhianLopes** [comment]
Boa tarde Ricardo!

Que ótimo que gostou! Fiz com a intenção de ajudar e principalmente meus
colegas!

Boa a dica que passou! Um outro amigo me passou a dica de montar vários
Wiki, dividindo assim pelos subtítulos, assim fica com maior agilidade de
acesso!

Se quiser dar uma olhada,  https://github.com/RhianLopes/Git/wiki

Mas com certeza irei usar sua dica, caso não nesse repositório, usarei em
outros, pois, estou construindo com o Pattern que eu uso em um projeto
BackEnd em Java.

Ainda estou construindo, mas se já quiser dar uma olhada:
https://github.com/RhianLopes/Pattern-Java

Sigo a disposição!

Att Rhian

Em qui., 2 de jan. de 2020 às 12:50, Ricardo Kovalski <
notifications@github.com> escreveu:
